# NumPy Arrays — Example 01

NumPy is the library that gives Python a real array type.

A Python list can hold anything — a string next to a number next to a boolean.
A NumPy array holds **one type only**, packed together in one block of memory.

Backend analogy: a Python list is like `ArrayList<Object>`. A NumPy array is
like `int[]`. The `int[]` is stricter, but it is much faster and it lets you do
math on the whole array in one line.

This notebook walks through:

1. A plain Python list (the starting point)
2. Making an array with `np.array()`
3. Dimensions — 0-D, 1-D, 2-D, 3-D, 4-D
4. Data types inside an array
5. Indexing (positive and negative)
6. Slicing
7. Looping and searching
8. Sorting, inserting, deleting, flipping, appending

## 1. Start with a plain Python list

Before NumPy, this is what we had. A list can mix types and it grows freely.

In [1]:
arr1 = ['pune', "mumbai", 'surat', "kolkata", 'bihar', "jaipur", 'chennai']
arr1

['pune', 'mumbai', 'surat', 'kolkata', 'bihar', 'jaipur', 'chennai']

In [2]:
type(arr1)

list

In [3]:
# lists are indexed from 0
arr1[0]

'pune'

`type(arr1)` says `list`. Index `0` is the first item, not the second. That
part is the same in NumPy.

## 2. Turn a list into a NumPy array

`numpy.array()` takes a list and gives back an `ndarray` — the NumPy array
type. The name `ndarray` means "n-dimensional array".

In [4]:
import numpy

arr2 = numpy.array([10, 20, 30, 40, 50])
arr2

array([10, 20, 30, 40, 50])

In [5]:
type(arr2)

numpy.ndarray

The type is `numpy.ndarray`, not `list`. It looks like a list on screen but it
is a different object with different powers.

Now see the two ways of showing it.

In [6]:
print(arr2)

[10 20 30 40 50]


In [7]:
arr2

array([10, 20, 30, 40, 50])

`print(arr2)` shows `[10 20 30 40 50]` — no commas, just spaces. That is the
friendly view.

Typing `arr2` alone shows `array([10, 20, 30, 40, 50])` — the exact code you
would write to rebuild it. That is the developer view. Same array, two ways of
printing.

A tuple works too. NumPy only needs something it can walk through.

In [8]:
arr3 = numpy.array((100, 200, 300, 400, 500))
arr3

array([100, 200, 300, 400, 500])

In [9]:
type(arr3)

numpy.ndarray

Still `numpy.ndarray`. The tuple was only the input container — once inside
NumPy it is an array like any other.

## 3. The short name `np`

Nobody types `numpy.` all day. Everyone imports it as `np`. Treat this as the
standard — every tutorial, every codebase, every StackOverflow answer uses it.

In [10]:
import numpy as np

## 4. Dimensions — how many brackets deep is the data?

Dimension = how many index numbers you need to reach one value.

| Dimensions | Called | Real-world shape | Index needed |
|---|---|---|---|
| 0-D | scalar | a single number | none |
| 1-D | vector | a row of numbers | `a[i]` |
| 2-D | matrix | a table (rows × columns) | `a[i, j]` |
| 3-D | tensor | a stack of tables | `a[i, j, k]` |

`.ndim` tells you the number of dimensions. `.shape` tells you how big each
dimension is.

In [11]:
# 0-D array (scalar)
a0 = np.array(5)
a0

array(5)

In [12]:
a0.ndim, a0.shape

(0, ())

`ndim` is `0` and `shape` is `()` — an empty tuple. There is no length to
report because there is no axis at all. It is one lonely number wrapped in a
NumPy box.

In [13]:
# 1-D array
a1 = np.array([0, 1, 2, 3])
a1

array([0, 1, 2, 3])

In [14]:
a1.ndim, a1.shape

(1, (4,))

One pair of brackets → `ndim` is `1`. Shape `(4,)` means one axis holding 4
items. The trailing comma is just Python's way of writing a one-item tuple.

In [15]:
# 2-D array
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a2.ndim, a2.shape

(2, (2, 3))

Brackets inside brackets → `ndim` is `2`. Shape `(2, 3)` reads as
**2 rows, 3 columns**. Rows always come first.

In [17]:
# 3-D array
a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
a3.ndim, a3.shape

(3, (2, 2, 2))

Three levels of brackets → `ndim` is `3`. Shape `(2, 2, 2)` reads as
**2 blocks, each 2 rows, each row 2 columns**.

In [19]:
# 4-D array -> each extra pair of brackets adds one more dimension
a4 = np.array([[[[4, 44, 444, 4444]]]])
a4

array([[[[   4,   44,  444, 4444]]]])

In [20]:
a4.ndim, a4.shape

(4, (1, 1, 1, 4))

Shape `(1, 1, 1, 4)` — three wrapper layers of size 1, then the 4 real values.
The wrappers hold no extra data. They only add depth.

There is a shortcut for this. `ndmin=` tells NumPy the minimum number of
dimensions you want, and it adds the wrapper brackets for you.

In [21]:
a4b = np.array([4, 44, 444, 4444], ndmin=4)
a4b

array([[[[   4,   44,  444, 4444]]]])

In [22]:
a4b.ndim, a4b.shape

(4, (1, 1, 1, 4))

Same result as writing `[[[[...]]]]` by hand — `ndim` 4, shape `(1, 1, 1, 4)`.
Less typing and far fewer mismatched brackets.

## 5. Data types — one type for the whole array

This is the biggest difference from a Python list. A list keeps each item's own
type. An array must pick **one type for everything**.

If you hand it mixed types, NumPy does not throw an error. It quietly promotes
everything to the one type that can hold them all. This is called **upcasting**.

The promotion ladder is: `bool` → `int` → `float` → `string`. The widest type
in your data wins.

In [23]:
amix1 = np.asarray([True, 5, 5.0, "Kali"])
amix1

array(['True', '5', '5.0', 'Kali'], dtype='<U32')

A string was in the list, so **everything** became a string. Look at the
output: `'True'`, `'5'`, `'5.0'` are now text in quotes. The dtype `<U21` means
"unicode string, up to 21 characters".

Once this happens you cannot do maths on the array any more. This is a common
silent bug — one stray text value in a CSV column turns the whole column into
strings.

In [24]:
amix1.dtype

dtype('<U32')

Now the same idea with only booleans and numbers.

In [25]:
amix2 = np.array([True, 5])
amix2

array([1, 5])

`True` became `1`. Booleans sit at the bottom of the ladder, so integers win.

In [26]:
amix3 = np.array([False, 10])
amix3

array([ 0, 10])

`False` became `0`. Same rule.

In [27]:
amix4 = np.array([True, 'shridhar', 5, 5.0])
amix4

array(['True', 'shridhar', '5', '5.0'], dtype='<U32')

A string is present again, so all four values became text — `dtype='<U32'`.

### Choosing the type yourself

You do not have to accept NumPy's guess. Pass `dtype=` and it converts for you.

In [28]:
amix5 = np.asarray([False, 10], dtype=np.int32)
amix5

array([ 0, 10], dtype=int32)

`int32` means each number uses 32 bits. NumPy's default on most machines is
`int64`. Choosing `int32` halves the memory when you know the values are small
— the same trade-off as picking `int` over `long` in Java.

In [29]:
amix6 = np.array([1, 5.55, 2, 6.9], dtype=np.float64)
amix6

array([1.  , 5.55, 2.  , 6.9 ])

`1` and `2` are shown as `1.` and `2.` — the trailing dot means they are now
floats, not integers. The whole array is `float64`.

## 6. Indexing — reading one value

Give one index number per dimension. A 2-D array needs two numbers, a 3-D array
needs three, and so on. Order goes outside-in: block, then row, then column.

In [30]:
# indexing a 1-D array
a1[0], a1[1], a1[-1]

(np.int64(0), np.int64(1), np.int64(3))

`a1[-1]` is the last item. Negative numbers count backwards from the end, so
you never need `len(a1) - 1`.

In [31]:
# indexing a 2-D array -> row first, then column
a2[1]          # whole row at index 1

array([4, 5, 6])

One index on a 2-D array returns a whole **row**, not a single value. The row
is itself a 1-D array.

In [32]:
a2[1][2], a2[1, 2]   # same element, two ways to write it

(np.int64(6), np.int64(6))

Both give `6`.

`a2[1][2]` does two steps: fetch row 1, then item 2 of that row.
`a2[1, 2]` does it in one step. The comma form is the NumPy way — it is faster
because it does not build the temporary row in between. Lists cannot do the
comma form at all.

In [33]:
# indexing a 3-D array -> block first, then row, then column
a3[1]          # whole 2x2 block at index 1

array([[5, 6],
       [7, 8]])

In [34]:
a3[1][0]       # row 0 inside block 1

array([5, 6])

In [35]:
a3[1][0][1], a3[1, 0, 1]   # single element, two ways to write it

(np.int64(6), np.int64(6))

Each index peels off one layer: block → row → value.

In [36]:
# indexing a 4-D array -> peel off one bracket layer at a time
a4[0]          # drops to 3-D: shape (1, 1, 4)

array([[[   4,   44,  444, 4444]]])

In [37]:
a4[0][0][0], a4[0, 0, 0]      # drops to 1-D: array([4, 44, 444, 4444])

(array([   4,   44,  444, 4444]), array([   4,   44,  444, 4444]))

In [38]:
a4[0, 0, 0, 2]      # single element -> 444

np.int64(444)

Four dimensions need four indexes to reach a value. Three indexes still leave
you holding an array.

### Negative indexing

In [39]:
arr2

array([10, 20, 30, 40, 50])

In [40]:
arr2[-1]

np.int64(50)

In [41]:
arr2[-2]

np.int64(40)

`-1` is the last item, `-2` is the second from last. Handy when you do not know
the length.

### When the index does not exist

Ask for an index past the end and NumPy raises `IndexError`. It does not return
`None` and it does not grow the array.

In [42]:
a12 = np.array([1, 2, 3])
a12

array([1, 2, 3])

In [43]:
a12[3]      # only 0, 1, 2 exist -> IndexError

IndexError: index 3 is out of bounds for axis 0 with size 3

Read the message carefully: *"index 3 is out of bounds for axis 0 with size 3"*.
It tells you three things — the bad index, **which axis** it was on, and how big
that axis actually is. On a multi-dimensional array the axis number tells you
exactly which bracket position you got wrong.

In [44]:
a4[0, 0, 1, 0]      # axis 2 has size 1, so index 1 is too big

IndexError: index 1 is out of bounds for axis 2 with size 1

Here the first two indexes were fine. Axis 2 has size 1, so its only valid
index is `0`.

## 7. Slicing — reading many values

The pattern is `array[start : stop : step]`.

- `start` is included
- `stop` is **excluded**
- `step` is how far to jump each time

Leave any of them out and NumPy fills in a sensible default: start `0`,
stop `end`, step `1`.

In [45]:
arr2

array([10, 20, 30, 40, 50])

In [46]:
arr2[1:]        # from index 1 to the end

array([20, 30, 40, 50])

In [47]:
arr2[:3]        # from the start up to (not including) index 3

array([10, 20, 30])

`arr2[:3]` gives 3 items — indexes 0, 1, 2. Index 3 is left out. That
"stop is excluded" rule is the one people trip on.

In [48]:
arr2[:]         # everything

array([10, 20, 30, 40, 50])

In [49]:
arr2[1:4:1]     # start 1, stop 4, step 1

array([20, 30, 40])

In [50]:
arr2[1:4:2]     # same window, but skip every other item

array([20, 40])

Step `2` takes index 1, skips 2, takes 3. Result: `[20, 40]`.

In [51]:
arr2[:4:3]      # start 0, stop 4, step 3

array([10, 40])

Takes index 0, jumps 3, takes index 3. Result: `[10, 40]`.

In [52]:
arr2[::4]       # whole array, step 4

array([10, 50])

In [53]:
arr2[::]        # same as arr2[:]

array([10, 20, 30, 40, 50])

`arr2[::4]` takes index 0 and index 4 → `[10, 50]`.

One important difference from lists: **a NumPy slice is a view, not a copy.**
Change the slice and you change the original array. A Python list slice gives
you a fresh copy. Use `.copy()` when you really want a separate array.

## 8. Looping through an array

A `for` loop works exactly like it does on a list.

In [54]:
for i in arr2:
    print(i)

10
20
30
40
50


This is fine for printing. For maths, do **not** loop — write `arr2 * 2` and
NumPy does the whole array in one shot, in C. That is called vectorisation and
it is the main reason NumPy exists.

## 9. Searching with `np.where()`

`np.where(condition)` returns the **positions** where the condition is true —
not the values themselves.

In [55]:
x = np.where(arr2 == 20)
print(x)

(array([1]),)


The result is `(array([1]),)` — a tuple holding one array. The tuple has one
entry per dimension, so a 1-D array gives a 1-element tuple. Read it as
"value 20 sits at index 1".

In [56]:
x = np.where(arr2 == 50)
print(x)

(array([4]),)


Now a case with the same value repeated many times.

In [57]:
arrr = np.array([1, 2, 3, 1, 2, 3, 1, 2, 3])
arrr

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [58]:
x = np.where(arrr == 2)
print(x)

(array([1, 4, 7]),)


`(array([1, 4, 7]),)` — the value `2` appears at indexes 1, 4 and 7. Unlike
`list.index()`, which stops at the first hit, `np.where` finds every match.

## 10. Sorting

`np.sort()` returns a **new sorted array**. The original is untouched.

In [59]:
arraysort = np.array([2, 1, 5, 3, 7, 5, 9, 8, 5, 7, 3])
arraysort

array([2, 1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

In [60]:
np.sort(arraysort)

array([1, 2, 3, 3, 5, 5, 5, 7, 7, 8, 9])

In [61]:
arraysort      # unchanged

array([2, 1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

The sorted output came back, but `arraysort` is still in its original order.
`np.sort` is a copy-out function. To keep the result, assign it to a name.

## 11. Insert and delete

`np.insert(array, position, value)` puts a value at a position.

Same rule as sorting: it returns a **new array**. NumPy arrays are fixed size,
so "inserting" really means building a fresh, bigger array behind the scenes.

In [62]:
np.insert(arr2, 5, 60)      # add 60 at the end position

array([10, 20, 30, 40, 50, 60])

In [63]:
arr2      # still 5 items

array([10, 20, 30, 40, 50])

The original never changed. Assign the result if you want to keep it.

In [64]:
arrr1 = np.insert(arr2, 5, 60)
arrr1

array([10, 20, 30, 40, 50, 60])

In [65]:
np.insert(arraysort, 0, 100)     # insert at the front

array([100,   2,   1,   5,   3,   7,   5,   9,   8,   5,   7,   3])

Position `0` pushes everything else one step to the right.

In [66]:
np.delete(arraysort, 0)      # remove the item at index 0

array([1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

`np.delete(array, position)` removes by **position**, not by value. To delete
by value, find the position with `np.where` first.

You can also delete several positions at once by passing a list.

In [67]:
index = [0, 1, 2]
arrr2 = np.delete(arr2, index)
arrr2

array([40, 50])

In [68]:
arr2      # again, untouched

array([10, 20, 30, 40, 50])

Indexes 0, 1 and 2 were dropped, leaving `[40, 50]`.

## 12. Reversing with `np.flip()`

In [69]:
np.flip(arr2)

array([50, 40, 30, 20, 10])

In [70]:
arr2

array([10, 20, 30, 40, 50])

Reversed copy out, original unchanged — the same pattern yet again.

In [71]:
arrflip = np.flip(arr2)
arrflip

array([50, 40, 30, 20, 10])

## 13. Changing an array in place

Everything above returned a copy. These two actually modify the array.

First, plain assignment to an index.

In [72]:
arr2[0] = 100
arr2

array([100,  20,  30,  40,  50])

`arr2` really changed. Note the type rule still applies — assign `"hello"` into
an integer array and you get an error, because the array's dtype is locked in.

Second, the `.sort()` **method** (not the `np.sort()` function).

In [73]:
arr2.sort()

In [74]:
arr2

array([ 20,  30,  40,  50, 100])

Two things to notice:

1. `arr2.sort()` printed nothing — it returns `None`, like `list.sort()`.
2. `arr2` itself is now sorted.

So: `np.sort(a)` gives a sorted copy, `a.sort()` sorts in place. Mixing them up
(`a = a.sort()`) is a classic bug — it sets `a` to `None`.

## 14. Appending

`np.append()` looks like `list.append()` but behaves completely differently.

In [75]:
np.append(arr2, 1000)

array([  20,   30,   40,   50,  100, 1000])

In [76]:
arr2      # not appended

array([ 20,  30,  40,  50, 100])

The value was added in the returned array, but `arr2` is unchanged. Again — you
must assign the result.

And the method version simply does not exist.

In [77]:
arr2.append(1000)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

`AttributeError: 'numpy.ndarray' object has no attribute 'append'`.

This is not an oversight. A list can append cheaply because it keeps spare
room at the end. A NumPy array is one tight block of memory with no spare room,
so every "append" has to allocate a whole new block and copy everything across.
NumPy makes that cost visible by refusing to offer the method.

If you need to build up data item by item, use a Python list and convert once
at the end with `np.array(my_list)`.

## Recap

| What I wanted | What I wrote | Changes the original? |
|---|---|---|
| Make an array | `np.array([1, 2, 3])` | — |
| Count dimensions | `a.ndim` | no |
| Size of each dimension | `a.shape` | no |
| Force a type | `np.array([...], dtype=np.int32)` | — |
| Force a depth | `np.array([...], ndmin=4)` | — |
| Read one value | `a[1, 2]` | no |
| Read the last value | `a[-1]` | no |
| Read a range | `a[start:stop:step]` | no (but it is a view) |
| Find positions | `np.where(a == 20)` | no |
| Sorted copy | `np.sort(a)` | **no** |
| Sort in place | `a.sort()` | **yes** |
| Insert | `np.insert(a, pos, val)` | no |
| Delete | `np.delete(a, pos)` | no |
| Reverse | `np.flip(a)` | no |
| Add to the end | `np.append(a, val)` | no |
| Change one value | `a[0] = 100` | **yes** |

The pattern worth memorising: **almost every `np.something(array)` function
returns a copy.** If you forget to assign the result, your change disappears.
The only in-place operations here are direct assignment (`a[0] = 100`) and the
`.sort()` method.

### Three mistakes to avoid

1. One string in the data turns the **whole array** into strings — check
   `.dtype` when maths silently stops working.
2. `stop` in a slice is excluded. `a[:3]` gives 3 items, not 4.
3. `arr.append(x)` does not exist. Use `np.append(arr, x)` and assign the
   result — or build a Python list first.